# Generated by Django 4.2.10 on 2024-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SetupPerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_file", "Can view file"),
                    ("add_file", "Can add file"),
                    ("edit_file", "Can edit file"),
                    ("delete_file", "Can delete file"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
