# Generated by Django 4.2.10 on 2024-05-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_codeemail_email_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codeemail",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="codeemail",
            name="other_names",
        ),
        migrations.AlterField(
            model_name="codeemail",
            name="code",
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
